Contiki 2.5: ieee_15_4_manager Struct Reference
ieee_15_4_manager Struct Reference
[RF230 MAC]
The interface structure for the 802.15.4 quasi-MAC.
#include <cpu/avr/radio/ieee-manager/ieee-15-4-manager.h>
Data Fields
int(* wake)(void)
Turn the MAC layer on.
int(* sleep)(void)
Turn the MAC layer off.
void(* set_channel)(int channel)
Set the operating channel.
int(* get_channel)(void)
Get the operating channel.
void(* set_dst_panid)(int panid)
Set the Destination PAN_ID.
int(* get_dst_panid)(void)
Get the Destination PAN_ID.
void(* set_src_panid)(int panid)
Set the Source PAN_ID.
int(* get_src_panid)(void)
Get the Source PAN_ID.
void(* set_auto_mode)(bool mode)
Set the Automatic TRX modes.
bool(* get_auto_mode)(void)
Get the current state of Automatic TRX modes.
void(* set_long_addr)(uint64_t address)
Set the Long Address.
uint64_t(* get_long_addr)(void)
Get the Long Address.
void(* set_short_addr)(int address)
Set the Short Address.
int(* get_short_addr)(void)
Get the short Address.
void(* set_iamcoord_bit)(bool iamcoord)
Set the iAmCoord bit.
bool(* get_iamcoord_bit)(void)
Get the iAmCoord bit.
void(* set_coord_long_addr)(uint64_t address)
Set the Coordinator Long address.
uint64_t(* get_coord_long_addr)(void)
Get the Coordinator Long address.
void(* set_coord_short_addr)(int address)
Set the Coordinator Long address.
int(* get_coord_short_addr)(void)
Get the Coordinator Long address.
void(* set_dest_long_addr)(uint64_t address)
Set the Destination address.
uint64_t(* get_dest_long_addr)(void)
Get the Destination address.
Detailed Description
The interface structure for the 802.15.4 quasi-MAC.
Definition at line 54 of file ieee-15-4-manager.h.
Field Documentation
bool(* ieee_15_4_manager::get_auto_mode)(void)
Get the current state of Automatic TRX modes.
int(* ieee_15_4_manager::get_channel)(void)
Get the operating channel.
uint64_t(* ieee_15_4_manager::get_coord_long_addr)(void)
Get the Coordinator Long address.
int(* ieee_15_4_manager::get_coord_short_addr)(void)
Get the Coordinator Long address.
uint64_t(* ieee_15_4_manager::get_dest_long_addr)(void)
Get the Destination address.
int(* ieee_15_4_manager::get_dst_panid)(void)
Get the Destination PAN_ID.
Referenced by sicslowmac_dataRequest().
bool(* ieee_15_4_manager::get_iamcoord_bit)(void)
Get the iAmCoord bit.
uint64_t(* ieee_15_4_manager::get_long_addr)(void)
Get the Long Address.
Referenced by sicslowmac_dataRequest().
int(* ieee_15_4_manager::get_short_addr)(void)
Get the short Address.
int(* ieee_15_4_manager::get_src_panid)(void)
Get the Source PAN_ID.
Referenced by sicslowmac_dataRequest().
void(* ieee_15_4_manager::set_auto_mode)(bool mode)
Set the Automatic TRX modes.
void(* ieee_15_4_manager::set_channel)(int channel)
Set the operating channel.
void(* ieee_15_4_manager::set_coord_long_addr)(uint64_t address)
Set the Coordinator Long address.
void(* ieee_15_4_manager::set_coord_short_addr)(int address)
Set the Coordinator Long address.
void(* ieee_15_4_manager::set_dest_long_addr)(uint64_t address)
Set the Destination address.
void(* ieee_15_4_manager::set_dst_panid)(int panid)
Set the Destination PAN_ID.
void(* ieee_15_4_manager::set_iamcoord_bit)(bool iamcoord)
Set the iAmCoord bit.
void(* ieee_15_4_manager::set_long_addr)(uint64_t address)
Set the Long Address.
void(* ieee_15_4_manager::set_short_addr)(int address)
Set the Short Address.
void(* ieee_15_4_manager::set_src_panid)(int panid)
Set the Source PAN_ID.
int(* ieee_15_4_manager::sleep)(void)
Turn the MAC layer off.
int(* ieee_15_4_manager::wake)(void)
Turn the MAC layer on.