Contiki 2.5: Rime addresses
Rime addresses
[The Rime communication stack]
The rimeaddr module is an abstract representation of addresses in Rime.
Files
file rimeaddr.c
Functions for manipulating Rime addresses.
file rimeaddr.h
Header file for the Rime address representation.
Functions
void rimeaddr_copy (rimeaddr_t *dest, const rimeaddr_t *from)
Copy a Rime address.
int rimeaddr_cmp (const rimeaddr_t *addr1, const rimeaddr_t *addr2)
Compare two Rime addresses.
void rimeaddr_set_node_addr (rimeaddr_t *addr)
Set the address of the current node.
Variables
rimeaddr_t rimeaddr_node_addr
The Rime address of the node.
rimeaddr_t rimeaddr_node_addr
The Rime address of the node.
const rimeaddr_t rimeaddr_null
The null Rime address.
Detailed Description
The rimeaddr module is an abstract representation of addresses in Rime.
Function Documentation
int rimeaddr_cmp (const rimeaddr_t * addr1, const rimeaddr_t * addr2)
Compare two Rime addresses.
Parameters:
addr1 The first address
addr2 The second address
Returns:
Non-zero if the addresses are the same, zero if they are different
This function compares two Rime addresses and returns the result of the comparison. The function acts like the '==' operator and returns non-zero if the addresses are the same, and zero if the addresses are different.
Examples:
example-collect.c, example-multihop.c, example-runicast.c, and example-unicast.c.
Referenced by mac_LowpanToEthernet(), neighbor_info_packet_received(), neighbor_info_packet_sent(), and sicslowmac_dataRequest().
void rimeaddr_copy (rimeaddr_t * dest, const rimeaddr_t * from)
Copy a Rime address.
Parameters:
dest The destination
from The source
This function copies a Rime address from one location to another.
Examples:
example-collect.c, example-multihop.c, and example-runicast.c.
void rimeaddr_set_node_addr (rimeaddr_t * addr)
Set the address of the current node.
Parameters:
addr The address
This function sets the Rime address of the node.
Referenced by main().
Variable Documentation
rimeaddr_t rimeaddr_node_addr
The Rime address of the node.
This variable contains the Rime address of the node. This variable should not be changed directly; rather, the rimeaddr_set_node_addr() function should be used.
Definition at line 48 of file rimeaddr.c.
Referenced by broadcast_send(), and main().
rimeaddr_t rimeaddr_node_addr
The Rime address of the node.
This variable contains the Rime address of the node. This variable should not be changed directly; rather, the rimeaddr_set_node_addr() function should be used.
Examples:
example-announcement.c, example-collect.c, example-multihop.c, example-rucb.c, example-rudolph1.c, example-rudolph2.c, example-runicast.c, example-trickle.c, and example-unicast.c.
Definition at line 48 of file rimeaddr.c.
Referenced by broadcast_send(), and main().
const rimeaddr_t rimeaddr_null
The null Rime address.
This variable contains the null Rime address. The null address is used in route tables to indicate that the table entry is unused. Nodes with no configured address has the null address. Nodes with their node address set to the null address will have problems communicating with other nodes.
Examples:
example-collect.c.
Referenced by mac_LowpanToEthernet(), neighbor_info_packet_received(), neighbor_info_packet_sent(), and sicslowmac_dataRequest().